[build]
  base = "build"
  command = "node server.js"
  functions = "functions"
  publish = "build"

[dev]
  command = "npx frontity dev"
  framework = "#custom"
  targetPort = 3000
  port = 8888
  publish = "build"
  jwtRolePath = "app_metadata.authorization.roles"
  autoLaunch = true
